-- DROP USER niheyjkauxafdk;

-- CREATE USER niheyjkauxafdk WITH
--   LOGIN
--   NOSUPERUSER
--   INHERIT
--   CREATEDB
--   CREATEROLE
--   NOREPLICATION
--   PASSWORD '3aa11f4917ebf5282d520ccfb544bdab1addaaa754ce78bca9a3872283dd3315';


-- DROP DATABASE d34tqia6t0iqe5;
--
-- CREATE DATABASE d34tqia6t0iqe5
-- WITH
-- OWNER = niheyjkauxafdk
-- ENCODING = 'UTF8'
-- LC_COLLATE = 'Spanish_United States.1252'
-- LC_CTYPE = 'Spanish_United States.1252'
-- TABLESPACE = pg_default
-- CONNECTION LIMIT = -1;

CREATE SCHEMA IF NOT EXISTS ASM;
CREATE SCHEMA IF NOT EXISTS META;
CREATE SCHEMA IF NOT EXISTS DIAGRAMS;
CREATE SCHEMA IF NOT EXISTS PERSONS;